require 'rake'

# Generates rdoc for the various files under the (autogenerated) rdoc
# directory.
#
# TODO: Add more documents to generate
#
task :docs do
   require "rdoc/rdoc"
   dest_dir = Dir.pwd + "/rdoc"
   rdoc = RDoc::RDoc.new
   rdoc.document(["doc/ToDo", "-o#{dest_dir}"])
end

# Runs the DBI test suite (though not the various DBD tests)
task :test do
	system("ruby test/ts_dbi.rb")
end

task :default => :test